### PR TITLE
DOCSP-19218 Adds kubernetes operator v1.9 to deprecated versions

### PR DESCRIPTION
**Pull request by mongodbchez**
[Jira](https://jira.mongodb.org/browse/DOCSP-19218)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=617701a8c13055282d6fc978)
[Staging link](https://docs-mongodbcom-staging.corp.mongodb.com/legacy/)

### CODE REVIEW

**Comment by mongodbchez** [comment]
@jwilliams-mongo should this be assigned to @i80and for tech review like the sample PR? Or is it ok to skip tech review?

**Comment by jwilliams-mongo** [comment]
@mongodbchez DOP does most of the work in this repo, so I'd get a sign off just to be sure.

**Comment by jwilliams-mongo** [comment]
It doesn't necessarily have to be @i80and -- you can post to #snooty-platform to ask for a review.

**Review by rayangler — APPROVED** [review]
LGTM!

Tested it on this [staging link](https://docs-mongodbcom-staging.corp.mongodb.com/DOCSP-19218/landing/raymundrodriguez/master/legacy/) and can confirm that the dropdown can lead to v1.9. Feel free to merge when you're ready!

**Comment by mongodbchez** [comment]
Cheers thanks @rayangler

**Pull request merged**
