### PR TITLE
DOP-3185: update icons in landing

### PR DESCRIPTION
**Pull request by seungpark**
Updating icons in docs landing according to [figma design](https://www.figma.com/file/PctpWXNmlv0khZahanOsU7/FY22-New-Brand?node-id=995%3A17299)

[current behavior](https://www.mongodb.com/docs/)

[staging link](https://docs-mongodbcom-integration.corp.mongodb.com/530f704fc6b0d41d5bb0c128c9fa71d0e951bd74/DOP-3185/landing/seung.park/DOP-3185/)

**notes:**
- staging site is off a working branch in snooty to update icon sizing https://github.com/mongodb/snooty/tree/DOP-3185

### CODE REVIEW

**Comment by jdestefano-mongo** [comment]
@seungpark Seeing this when I try to access the staging link
image

**Review by allisonmui9 — CHANGES_REQUESTED** [review]
I wasn't sure if you covered this or missed it! But could you add staging links for the product landing pages too? We need to make sure we update those icons as well. 
Landing pages for - MCLI, compass, server, atlas, atlas search. Icons are used in the bottom card.

**Comment by seungpark** [comment]
> I wasn't sure if you covered this or missed it! But could you add staging links for the product landing pages too? We need to make sure we update those icons as well. Landing pages for - MCLI, compass, server, atlas, atlas search. Icons are used in the bottom card.

yup these are all in done in respective docs' repositories. will group them in this PR https://github.com/mongodb/snooty/pull/675

**Review by schmalliso — APPROVED** [review]

**Comment by seungpark** [comment]
merging as @allisonmui9 gave an approval in the snooty PR

**Pull request merged**
